name: Unit Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install 
        run: |
          yarn install --frozen-lockfile
      - name: Unit tests
        run: |
          yarn run test